---
title: "Municípios"
---

In [1]:
import pandas as pd
from utils import get_path

# Descrição

Informações referentes a localizações em diversas escalas (Município, Regiões de Saúde, UF, Região).

# Fontes de dados

## Municípios

[Fonte Municípios](https://github.com/kelvins/Municipios-Brasileiros)

### Carregando tabela

In [2]:
url_muns = 'https://raw.githubusercontent.com/kelvins/Municipios-Brasileiros/main/csv/municipios.csv'
df_muns = pd.read_csv(url_muns)
df_muns

,codigo_ibge,nome,latitude,longitude,capital,codigo_uf,siafi_id,ddd,fuso_horario
0,5200050,Abadia de Goiás,-16.75730,-49.4412,0,52,1050,62,America/Sao_Paulo
1,3100104,Abadia dos Dourados,-18.48310,-47.3916,0,31,4001,34,America/Sao_Paulo
2,5200100,Abadiânia,-16.19700,-48.7057,0,52,9201,62,America/Sao_Paulo
3,3100203,Abaeté,-19.15510,-45.4444,0,31,4003,37,America/Sao_Paulo
4,1500107,Abaetetuba,-1.72183,-48.8788,0,15,401,91,America/Sao_Paulo
...,...,...,...,...,...,...,...,...,...
5565,2933604,Xique-Xique,-10.82300,-42.7245,0,29,3971,74,America/Sao_Paulo
5566,2517407,Zabelê,-8.07901,-37.1057,0,25,542,83,America/Sao_Paulo
5567,3557154,Zacarias,-21.05060,-50.0552,0,35,2973,18,America/Sao_Paulo
5568,2114007,Zé Doca,-3.27014,-45.6553,0,21,1287,98,America/Sao_Paulo
5569,4219853,Zortéa,-27.45210,-51.5520,0,42,950,49,America/Sao_Paulo

### Selecionando colunas

In [3]:
cols_muns = [
  'codigo_ibge',
  'nome',
  'capital',
  'codigo_uf',
  'latitude',
  'longitude',
]

In [4]:
df_muns = df_muns[cols_muns]
df_muns

,codigo_ibge,nome,capital,codigo_uf,latitude,longitude
0,5200050,Abadia de Goiás,0,52,-16.75730,-49.4412
1,3100104,Abadia dos Dourados,0,31,-18.48310,-47.3916
2,5200100,Abadiânia,0,52,-16.19700,-48.7057
3,3100203,Abaeté,0,31,-19.15510,-45.4444
4,1500107,Abaetetuba,0,15,-1.72183,-48.8788
...,...,...,...,...,...,...
5565,2933604,Xique-Xique,0,29,-10.82300,-42.7245
5566,2517407,Zabelê,0,25,-8.07901,-37.1057
5567,3557154,Zacarias,0,35,-21.05060,-50.0552
5568,2114007,Zé Doca,0,21,-3.27014,-45.6553
5569,4219853,Zortéa,0,42,-27.45210,-51.5520

## Unidades Federativas

[Fonte Unidades Federativas](https://sistemasweb.agricultura.gov.br/manuais/Manual_PGA_WS/322CodigoIBGESigladaUnidadeFeder.html)

### Carregando tabela

In [5]:
url_ufs = 'https://sistemasweb.agricultura.gov.br/manuais/Manual_PGA_WS/322CodigoIBGESigladaUnidadeFeder.html'
df_ufs = pd.read_html(url_ufs)[0]
df_ufs.columns = ['codigo_uf', 'Sigla']
df_ufs

    codigo_uf Sigla
0          11    RO
1          12    AC
2          13    AM
3          14    RR
4          15    PA
5          16    AP
6          17    TO
7          21    MA
8          22    PI
9          23    CE
10         24    RN
11         25    PB
12         26    PE
13         27    AL
14         28    SE
15         29    BA
16         31    MG
17         32    ES
18         33    RJ
19         35    SP
20         41    PR
21         42    SC
22         43    RS
23         50    MS
24         51    MT
25         52    GO
26         53    DF
27         99    BR

## Regiões do Brasil

[Fonte Regiões do Brasil](https://www.estadosecapitaisdobrasil.com/)

### Carregando tabela

In [6]:
url_regs = 'https://www.estadosecapitaisdobrasil.com/'
df_regs = pd.read_html(url_regs)[0]
df_regs

    Bandeira               Estado Sigla         Capital        Região
0        NaN                 Acre    AC      Rio Branco         Norte
1        NaN              Alagoas    AL          Maceió      Nordeste
2        NaN                Amapá    AP          Macapá         Norte
3        NaN             Amazonas    AM          Manaus         Norte
4        NaN                Bahia    BA        Salvador      Nordeste
5        NaN                Ceará    CE       Fortaleza      Nordeste
6        NaN     Distrito Federal    DF        Brasília  Centro-Oeste
7        NaN       Espírito Santo    ES         Vitória       Sudeste
8        NaN                Goiás    GO         Goiânia  Centro-Oeste
9        NaN             Maranhão    MA        São Luís      Nordeste
10       NaN          Mato Grosso    MT          Cuiabá  Centro-Oeste
11       NaN   Mato Grosso do Sul    MS    Campo Grande  Centro-Oeste
12       NaN         Minas Gerais    MG  Belo Horizonte       Sudeste
13       NaN                 Pará    PA           Belém         Norte
14       NaN              Paraíba    PB     João Pessoa      Nordeste
15       NaN               Paraná    PR        Curitiba           Sul
16       NaN           Pernambuco    PE          Recife      Nordeste
17       NaN                Piauí    PI        Teresina      Nordeste
18       NaN       Rio de Janeiro    RJ  Rio de Janeiro       Sudeste
19       NaN  Rio Grande do Norte    RN           Natal      Nordeste
20       NaN    Rio Grande do Sul    RS    Porto Alegre           Sul
21       NaN             Rondônia    RO     Porto Velho         Norte
22       NaN              Roraima    RR       Boa Vista         Norte
23       NaN       Santa Catarina    SC   Florianópolis           Sul
24       NaN            São Paulo    SP       São Paulo       Sudeste
25       NaN              Sergipe    SE         Aracaju      Nordeste
26       NaN            Tocantins    TO          Palmas         Norte

### Selecionando colunas

In [7]:
cols_regs = [
  'Sigla',
  'Estado',
  'Região',
]

In [8]:
df_regs = df_regs[cols_regs]
df_regs

   Sigla               Estado        Região
0     AC                 Acre         Norte
1     AL              Alagoas      Nordeste
2     AP                Amapá         Norte
3     AM             Amazonas         Norte
4     BA                Bahia      Nordeste
5     CE                Ceará      Nordeste
6     DF     Distrito Federal  Centro-Oeste
7     ES       Espírito Santo       Sudeste
8     GO                Goiás  Centro-Oeste
9     MA             Maranhão      Nordeste
10    MT          Mato Grosso  Centro-Oeste
11    MS   Mato Grosso do Sul  Centro-Oeste
12    MG         Minas Gerais       Sudeste
13    PA                 Pará         Norte
14    PB              Paraíba      Nordeste
15    PR               Paraná           Sul
16    PE           Pernambuco      Nordeste
17    PI                Piauí      Nordeste
18    RJ       Rio de Janeiro       Sudeste
19    RN  Rio Grande do Norte      Nordeste
20    RS    Rio Grande do Sul           Sul
21    RO             Rondônia         Norte
22    RR              Roraima         Norte
23    SC       Santa Catarina           Sul
24    SP            São Paulo       Sudeste
25    SE              Sergipe      Nordeste
26    TO            Tocantins         Norte

# Gerando tabela

## Unindo tabelas

Merge

In [9]:
df_munic = df_muns.copy()
df_munic['codigo_ibge'] = df_munic['codigo_ibge'].apply(lambda x: int(str(x)[:6]))
df_munic = df_munic.merge(df_ufs, how='left', on='codigo_uf')
df_munic = df_munic.merge(df_regs, how='left', on='Sigla')
df_munic

,codigo_ibge,nome,capital,codigo_uf,latitude,longitude,Sigla,Estado,Região
0,520005,Abadia de Goiás,0,52,-16.75730,-49.4412,GO,Goiás,Centro-Oeste
1,310010,Abadia dos Dourados,0,31,-18.48310,-47.3916,MG,Minas Gerais,Sudeste
2,520010,Abadiânia,0,52,-16.19700,-48.7057,GO,Goiás,Centro-Oeste
3,310020,Abaeté,0,31,-19.15510,-45.4444,MG,Minas Gerais,Sudeste
4,150010,Abaetetuba,0,15,-1.72183,-48.8788,PA,Pará,Norte
...,...,...,...,...,...,...,...,...,...
5565,293360,Xique-Xique,0,29,-10.82300,-42.7245,BA,Bahia,Nordeste
5566,251740,Zabelê,0,25,-8.07901,-37.1057,PB,Paraíba,Nordeste
5567,355715,Zacarias,0,35,-21.05060,-50.0552,SP,São Paulo,Sudeste
5568,211400,Zé Doca,0,21,-3.27014,-45.6553,MA,Maranhão,Nordeste
5569,421985,Zortéa,0,42,-27.45210,-51.5520,SC,Santa Catarina,Sul

## Ajustando Colunas

In [10]:
cols_munic = {
  'codigo_ibge': 'cod_municipio',
  'nome': 'nome_municipio',
  'capital': 'capital',
  'Sigla': 'uf',
  'codigo_uf': 'cod_uf',
  'Estado': 'nome_uf',
  'Região': 'regiao',
  'latitude': 'latitude',
  'longitude': 'longitude',
}

In [11]:
df_munic = df_munic[list(cols_munic)]
df_munic = df_munic.rename(columns=cols_munic)
df_munic

,cod_municipio,nome_municipio,capital,uf,cod_uf,nome_uf,regiao,latitude,longitude
0,520005,Abadia de Goiás,0,GO,52,Goiás,Centro-Oeste,-16.75730,-49.4412
1,310010,Abadia dos Dourados,0,MG,31,Minas Gerais,Sudeste,-18.48310,-47.3916
2,520010,Abadiânia,0,GO,52,Goiás,Centro-Oeste,-16.19700,-48.7057
3,310020,Abaeté,0,MG,31,Minas Gerais,Sudeste,-19.15510,-45.4444
4,150010,Abaetetuba,0,PA,15,Pará,Norte,-1.72183,-48.8788
...,...,...,...,...,...,...,...,...,...
5565,293360,Xique-Xique,0,BA,29,Bahia,Nordeste,-10.82300,-42.7245
5566,251740,Zabelê,0,PB,25,Paraíba,Nordeste,-8.07901,-37.1057
5567,355715,Zacarias,0,SP,35,São Paulo,Sudeste,-21.05060,-50.0552
5568,211400,Zé Doca,0,MA,21,Maranhão,Nordeste,-3.27014,-45.6553
5569,421985,Zortéa,0,SC,42,Santa Catarina,Sul,-27.45210,-51.5520

# Exportando tabela

In [12]:
path_munic = get_path('LOCALIDADES', 'municipios.csv.gzip')
df_munic.to_csv(path_munic, index=False)

In [13]:
pd.read_csv(path_munic)

,cod_municipio,nome_municipio,capital,uf,cod_uf,nome_uf,regiao,latitude,longitude
0,520005,Abadia de Goiás,0,GO,52,Goiás,Centro-Oeste,-16.75730,-49.4412
1,310010,Abadia dos Dourados,0,MG,31,Minas Gerais,Sudeste,-18.48310,-47.3916
2,520010,Abadiânia,0,GO,52,Goiás,Centro-Oeste,-16.19700,-48.7057
3,310020,Abaeté,0,MG,31,Minas Gerais,Sudeste,-19.15510,-45.4444
4,150010,Abaetetuba,0,PA,15,Pará,Norte,-1.72183,-48.8788
...,...,...,...,...,...,...,...,...,...
5565,293360,Xique-Xique,0,BA,29,Bahia,Nordeste,-10.82300,-42.7245
5566,251740,Zabelê,0,PB,25,Paraíba,Nordeste,-8.07901,-37.1057
5567,355715,Zacarias,0,SP,35,São Paulo,Sudeste,-21.05060,-50.0552
5568,211400,Zé Doca,0,MA,21,Maranhão,Nordeste,-3.27014,-45.6553
5569,421985,Zortéa,0,SC,42,Santa Catarina,Sul,-27.45210,-51.5520